fix(database config): addition of testOnBorrow="true" in both connection pools
Adding testOnBorrow="true" to cope with MYSQL CommunicationsException.
Exception was:
The last packet successfully received from the server was 45 869 049 milliseconds ago.
SocketException: Software caused connection abort: socket write error

Closes [BS-16184](https://bonitasoft.atlassian.net/browse/BS-16184)